[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bm25s[core]>=0.3.10",
    "chonkie[code,hub]>=1.7.0",
    "chromadb>=1.5.9",
    "fire>=0.7.1",
    "langchain-text-splitters>=1.1.2",
    "magika>=1.0.3",
    "ollama>=0.6.2",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
]
